[package]
name = "cryptographic-message-syntax"
version = "0.28.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2024"
rust-version = "1.86"
license = "MPL-2.0"
description = "A pure Rust implementation of Crypographic Message Syntax (RFC 5652)"
keywords = ["cms", "rfc5652", "apple", "codesign"]
homepage = "https://github.com/indygreg/cryptography-rs"
repository = "https://github.com/indygreg/cryptography-rs.git"
readme = "README.md"

[dependencies]
bcder = "0.7.7"
bytes = "1.12.1"
hex = "0.4.3"
jiff = { version = "0.2.35", default-features = false, features = ["std"] }
pem = "4.0.0"
rand = { version = "0.10.2", optional = true }
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "rustls"], optional = true }
signature = "3.0.0"
subtle = "2.6.1"

[dependencies.x509-certificate]
path = "../x509-certificate"
version = "0.25.0"
features = ["test"]

[features]
default = ["http"]
http = ["dep:rand", "dep:reqwest"]
